version: '3'
services:
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feed
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./backend:/app
  frontend: 
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend-dev
      - database